# Site settings
title: Orkos MC
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  -  url: "#"
     icon: facebook.png
  -  url: "#"
     icon: gplus.png
  -  url: "#"
     icon: twitter.png
  -  url: "#"
     icon: rss.png

logo:
  text1: "Photographer"
  text2: "by HTML5 UP"
